name: Release

concurrency:
  group: release-${{ github.event.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        target:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            artifact-name: postgres-migrator-bin-linux-x64
            packages: musl-tools
          - target: x86_64-apple-darwin
            os: macos-latest
            artifact-name: postgres-migrator-bin-macos-x64
          - target: aarch64-apple-darwin
            os: macos-latest
            artifact-name: postgres-migrator-bin-macos-arm64
    runs-on: ${{ matrix.target.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target.target }}

      - name: Install packages
        if: matrix.target.os == 'ubuntu-latest' && matrix.target.packages
        run: sudo apt install ${{ matrix.target.packages }} -y

      - name: Build project
        run: cargo build --release --target ${{ matrix.target.target }}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target.artifact-name }}
          path: target/${{ matrix.target.target }}/release/postgres_migrator

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: postgres-migrator-bin-linux-x64
          path: bin/linux-x64

      - uses: actions/download-artifact@v2
        with:
          name: postgres-migrator-bin-macos-x64
          path: bin/macos-x64

      - uses: actions/download-artifact@v2
        with:
          name: postgres-migrator-bin-macos-arm64
          path: bin/macos-arm64

      - name: Mark binaries as executable
        working-directory: bin
        run: |
          chmod +x linux-x64/postgres_migrator
          chmod +x macos-x64/postgres_migrator
          chmod +x macos-arm64/postgres_migrator

      - run: ls bin

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          scope: "@peykio"
          node-version: 16
      # - name: Create Release Pull Request or Publish Packages
      #   uses: changesets/action@v1
      #   with:
      #     commit: "📦 version packages"
      #     publish: npx changeset publish
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
